TARGET = imu_test1.bin

SRC = imu_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/UsbSerial.mk
include $(WACKYLIB_DIR)/Mpu9250.mk
# This must come last...
include ../../boards/board.mk




