TARGET = clock_test1.bin

SRC = clock_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/Pacer.mk
include $(WACKYLIB_DIR)/Pwm.mk
# This must come last...
include ../../boards/board.mk




