TARGET = radio_send.bin

SRC = radio_send.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/Nrf24.mk
include $(WACKYLIB_DIR)/Pacer.mk
# This must come last...
include ../../boards/board.mk




