TARGET = radio_rx_test1.bin

SRC = radio_rx_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/Nrf24.mk
include $(WACKYLIB_DIR)/UsbSerial.mk
# This must come last...
include ../../boards/board.mk




