TARGET = gameboard_test1.bin

SRC = gameboard_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/UsartSerial.mk
include $(WACKYLIB_DIR)/UartSerial.mk
include $(WACKYLIB_DIR)/UsbSerial.mk
include $(WACKYLIB_DIR)/Pacer.mk
include $(WACKYLIB_DIR)/Adc.mk
include $(WACKYLIB_DIR)/Pio.mk
# This must come last...
include ../../boards/board.mk
