TARGET = adc_test1.bin

SRC = adc_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/Pacer.mk
include $(WACKYLIB_DIR)/Adc.mk
include $(WACKYLIB_DIR)/UsbSerial.mk
# This must come last...
include ../../boards/board.mk




