TARGET = racer.bin

SRC = racer.cpp racer.h util.cpp util.hpp motor.cpp motor.hpp

BOARD=racer

WACKYLIB_DIR = ../../wackylib
include $(WACKYLIB_DIR)/Pacer.mk
include $(WACKYLIB_DIR)/Adc.mk
include $(WACKYLIB_DIR)/Pio.mk
include $(WACKYLIB_DIR)/Pwm.mk
include $(WACKYLIB_DIR)/UsbSerial.mk
include $(WACKYLIB_DIR)/UsartSerial.mk
include $(WACKYLIB_DIR)/Mpu9250.mk
include $(WACKYLIB_DIR)/Ltc2943.mk
include $(WACKYLIB_DIR)/Nrf24.mk
include $(WACKYLIB_DIR)/Twi.mk


include ../../boards/board.mk

