TARGET = pwm_test1.bin

SRC = pwm_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/UsbSerial.mk
include $(WACKYLIB_DIR)/Pwm.mk
# This must come last...
include ../../boards/board.mk




