TARGET = twi_test1.bin

SRC = twi_test1.cpp

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/UsbSerial.mk
include $(WACKYLIB_DIR)/Twi.mk
# This must come last...
include ../../boards/board.mk




